### ISSUE TITLE
Incorrect Ligatures-Hyphenation

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#83]
`/2018/04/25/das-kartell-teil-2-der-whistleblower` (prd)

<img width="489" alt="screen shot 2018-04-29 at 15 02 10" src="https://user-images.githubusercontent.com/410211/39406915-a7fc1390-4bbe-11e8-8336-aba9ab9a13a6.png">

hypen does it correctly:
<a href="https://beta.observablehq.com/@tpreusse/auto-hyphenation"><img width="381" alt="screen shot 2018-04-29 at 15 03 31" src="https://user-images.githubusercontent.com/410211/39406916-ab7d5326-4bbe-11e8-9c4b-2d9dde2cdd1b.png"></a>

**Comment by tpreusse** [comment]
Might be related to ligatures (`ffl`)

**Comment by tpreusse** [comment]
Will be fixed by https://github.com/orbiting/pdf/pull/86

**Comment by diegomura** [comment]
@tpreusse not sure if #86 will fix it, but I'll try after merging it.
I think the reason is that in the hyphenation step ligatures are just one glyph for us, so we currently cant transform them back to many glyphs if we want to add a hyphen on it.
Or we can either implement it (to which I think we will need to polish fontkit a bit more) or not consider ligatures as a valid break point. The first one is more correct, but also more complex to do. The second one will prevent this to happen, but we would also be missing a valid break point to happen

**Comment by tpreusse** [comment]
@diegomura tested it, #86 will fix it. I'm fine with continuing to workaround it—not breaking on ligatures for now.

**Comment by diegomura** [comment]
nice! 
Not that I recall, I think we are already keeping ligatures outside the hyphenation process. I'll have to double check.
Thanks!
